[package]
name = "xenforeignmemory"
version = "0.1.0"
authors = ["Mathieu Tarral <mathieu.tarral@protonmail.com>"]
edition = "2018"
description = "Safe bindings to xenforeignmemory"
readme = "README.md"
homepage = "https://github.com/Wenzel/xenforeignmemory"
repository = "https://github.com/Wenzel/xenforeignmemory"
license = "GPL-3.0-only"
keywords = ["xen", "xenforeignmemory"]
categories = ["api-bindings"]

[dependencies]
libloading = "0.6.1"
log = "0.4.8"
failure = "0.1.7"
xenforeignmemory-sys = { git = "https://github.com/Wenzel/xenforeignmemory-sys" }
